In [6]:
# %% 1. Imports
import sys                                               # path bootstrap
import dataclasses                                       # dataclasses.replace for raw updates
from pathlib import Path                                 # repo root discovery

for _candidate in [Path.cwd()] + list(Path.cwd().parents):
    if (_candidate / "gbp").is_dir() and (_candidate / "tests").is_dir():
        sys.path.insert(0, str(_candidate))
        break

# %% 1. Imports
from gbp.loaders import DataLoaderGraph, DataLoaderMockMinimal
from gbp.build.pipeline import build_model
from gbp.consumers.simulator import (
    OrganicFlowPhase, DemandPhase, Environment, EnvironmentConfig,
)

# %% 2. User config — единственная ручка
mock_config = {"n_stations": 8, "n_trips": 200, "n_days": 3, "num_resources":3, "resource_capacity":100}

# %% 3. Source → Raw → Resolved
mock_loader = DataLoaderMockMinimal(mock_config)
mock_loader.load_data()
raw = DataLoaderGraph(mock_loader).load()
resolved = build_model(raw)

# %% 4. Simulation
simulation_log = Environment(
    resolved,
    EnvironmentConfig(phases=[OrganicFlowPhase()], seed=42, scenario_id="run"),
).run()
log_tables = simulation_log.to_dataframes()

2026-04-26 11:28:10 [info     ] load_start                     loader=graph_core
2026-04-26 11:28:10 [debug    ] source_validated               loader=graph_core
2026-04-26 11:28:10 [debug    ] observed_flow_built            loader=graph_core rows=149
2026-04-26 11:28:10 [info     ] load_done                      facilities=8 loader=graph_core

In [ ]:
# I think it logs we have trips, inventary, mistakes, demand, supply
# So mistakes its simulation_rejected_dispatches_log
# We don't have supply, but we have simulation_unmet_demand_log.
# What is the difference between demand and unment demand?
# Also i have simulation_resource_log
# I my case i don't have resources. But i think i am generating them with default since they are missed.
# Ok. simulation resources just an empty table

In [24]:
DataLoaderGraph(mock_loader)._build_resources()

TypeError: DataLoaderGraph._build_resources() missing 1 required positional argument: 'entities'

In [14]:
ll = DataLoaderGraph(mock_loader)

temporal = ll._build_temporal()
entities = ll._build_entities()
behavior = ll._build_behavior(entities)
distance_data = ll._build_distance_matrix(entities) if ll._config.build_edges else {}
resources = ll._build_resources(entities)

In [23]:
entities.station_ids

['4000.01',
 '4013.02',
 '4026.03',
 '4039.04',
 '4052.05',
 '4065.06',
 '4078.07',
 '4091.08']

In [17]:
if not entities.depot_ids:
    print('aaaa')

aaaa

In [15]:
resources

{}

In [4]:
mock_loader.df_resource_capacities

  resource_id  capacity
0     truck_1       100
1     truck_2       100
2     truck_3       100

In [6]:
log_tables.keys()

dict_keys(['simulation_inventory_log', 'simulation_flow_log', 'simulation_resource_log', 'simulation_unmet_demand_log', 'simulation_rejected_dispatches_log'])

In [2]:
log_tables['simulation_resource_log']

Empty DataFrame
Columns: [period_index, period_id, resource_id, resource_category, current_facility_id, status, available_at_period, home_facility_id]
Index: []

In [9]:
log_tables['simulation_resource_log']

Empty DataFrame
Columns: [period_index, period_id, resource_id, resource_category, current_facility_id, status, available_at_period, home_facility_id]
Index: []

In [22]:
log_tables['simulation_inventory_log']

    period_index period_id facility_id commodity_category  quantity
0              0        p0     4000.01       classic_bike       4.0
1              0        p0     4000.01      electric_bike       4.0
2              0        p0     4013.02       classic_bike       3.0
3              0        p0     4013.02      electric_bike       2.0
4              0        p0     4026.03       classic_bike       4.0
5              0        p0     4026.03      electric_bike       7.0
6              0        p0     4039.04       classic_bike       2.0
7              0        p0     4039.04      electric_bike       5.0
8              0        p0     4052.05       classic_bike       7.0
9              0        p0     4052.05      electric_bike       3.0
10             0        p0     4065.06       classic_bike       3.0
11             0        p0     4065.06      electric_bike       3.0
12             0        p0     4078.07       classic_bike       6.0
13             0        p0     4078.07      electric_bike       2.0
14             0        p0     4091.08       classic_bike       5.0
15             0        p0     4091.08      electric_bike       7.0
16             1        p1     4000.01       classic_bike       2.0
17             1        p1     4000.01      electric_bike       7.0
18             1        p1     4013.02       classic_bike       4.0
19             1        p1     4013.02      electric_bike       1.0
20             1        p1     4026.03       classic_bike       3.0
21             1        p1     4026.03      electric_bike       6.0
22             1        p1     4039.04       classic_bike       3.0
23             1        p1     4039.04      electric_bike       7.0
24             1        p1     4052.05       classic_bike       8.0
25             1        p1     4052.05      electric_bike       2.0
26             1        p1     4065.06       classic_bike       4.0
27             1        p1     4065.06      electric_bike       6.0
28             1        p1     4078.07       classic_bike       9.0
29             1        p1     4078.07      electric_bike       5.0
30             1        p1     4091.08       classic_bike       9.0
31             1        p1     4091.08      electric_bike       9.0
32             2        p2     4000.01       classic_bike       7.0
33             2        p2     4000.01      electric_bike      14.0
34             2        p2     4013.02       classic_bike       3.0
35             2        p2     4013.02      electric_bike       2.0
36             2        p2     4026.03       classic_bike       6.0
37             2        p2     4026.03      electric_bike       9.0
38             2        p2     4039.04       classic_bike       4.0
39             2        p2     4039.04      electric_bike       5.0
40             2        p2     4052.05       classic_bike       4.0
41             2        p2     4052.05      electric_bike       3.0
42             2        p2     4065.06       classic_bike       5.0
43             2        p2     4065.06      electric_bike       4.0
44             2        p2     4078.07       classic_bike      13.0
45             2        p2     4078.07      electric_bike       1.0
46             2        p2     4091.08       classic_bike       8.0
47             2        p2     4091.08      electric_bike      12.0